name: Context
run-name: Show context information

on: push

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show github object JSON
        run: echo "${{ toJson(github) }}"
        