name: Copy repository files to virtual machine work directory

on: push

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Show work directory
        run: pwd
      - name: List work directory files before copy
        run: ls -lah
      - name: Copy repository files to work directory
        uses: actions/checkout@v4
      - name: List work directory files after copy
        run: ls -lah
