name: Issues

on: 
  issues:
    types: [opened, closed]

jobs:
  issue-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show default branch name
        run: echo $GITHUB_REF
      - name: Show last commit ID
        run: echo $GITHUB_SHA
        