name: Parent Workflow
run-name: Parent Workflow

on: 
  workflow_call:
    inputs:
      username:
        description: "Username"
        type: string
        required: true

jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: "Print username"
        run: echo "${{ inputs.username }}"
        