name: Result

on:
  workflow_run:
    workflows: [Hello]
    types: [completed]

jobs:
  success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Hello workflow result
        run : echo "Success!"
  
  failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Hello workflow result
        run : echo "Failed!"
    