name: Show Python Verions

on: push

jobs:
  show-python-linux:
    runs-on: ubuntu-latest
    name: Show Python version for Linux
    steps:
      - run: echo "Python version for Linux is:"
      - run: python3 --version

  show-python-windows:
    runs-on: windows-latest
    name: Show Python version for Windows
    steps:
      - run: echo "Python versiob for Windows is:"
      - run: python3 --version
      
  final-message:
    runs-on: macos-latest
    needs: [show-python-linux, show-python-windows]
    steps:
      - run: echo "All jobs finished!"
